### ISSUE TITLE
Vacuum is not visible in the image

### ISSUE THREAD

**Issue by sendorm** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Vacuum-Map-Camera#3]
My configuration is as follows:
```
  - platform: xiaomi_vacuum_map
    vacuum_ssh: "root@192.168.xxx.xxx"
    vacuum_entity: "vacuum.roborock"
```
I can see the map but the vacuum is not present in the image. Also the state of the camera entity has a long list of paths such as follows:

```
path:
  - x: 508.36
    'y': 514.88
    a: -1.515
  - x: 508.32
    'y': 514.84
    a: -1.514
  - x: 508.32
    'y': 514.9
    a: -1.51
  - x: 508.44
    'y': 514.9
    a: -1.519
  - x: 508.54
    'y': 514.68
    a: -1.537
  - x: 508.48
    'y': 515
    a: -1.523
  - x: 508.36
    'y': 514.7
    a: -1.515
  - x: 508.5
    'y': 514.68
    a: -1.537
...
...
```
